# Generated by Django 5.0.7 on 2024-07-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sir Name', max_length=500)),
                ('intro', models.CharField(default='intro', max_length=2000)),
                ('pointer1', models.TextField(default='1st point')),
                ('pointer2', models.TextField(default='2nd point')),
                ('pointer3', models.TextField(default='3rd point')),
                ('pointer4', models.TextField(default='4th point')),
                ('pointer5', models.TextField(default='5th point')),
                ('pointer6', models.TextField(default='6th point')),
                ('pointer7', models.TextField(default='7th point')),
            ],
        ),
    ]
