# Generated by Django 5.0.7 on 2024-07-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayurweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='Title of the Service', max_length=200)),
                ('service_desc', models.TextField()),
                ('icon_class', models.CharField(help_text='fa-solid fa-star', max_length=100)),
            ],
        ),
    ]
