# Generated by Django 5.0.7 on 2024-08-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayurweb', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_desc',
        ),
        migrations.AddField(
            model_name='service',
            name='desc_1',
            field=models.TextField(default='desc_1'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_10',
            field=models.TextField(default='desc_10'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_11',
            field=models.TextField(default='desc_11'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_12',
            field=models.TextField(default='desc_12'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_13',
            field=models.TextField(default='desc_13'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_14',
            field=models.TextField(default='desc_14'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_15',
            field=models.TextField(default='desc_15'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_16',
            field=models.TextField(default='desc_16'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_2',
            field=models.TextField(default='desc_2'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_3',
            field=models.TextField(default='desc_3'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_4',
            field=models.TextField(default='desc_4'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_5',
            field=models.TextField(default='desc_5'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_6',
            field=models.TextField(default='desc_6'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_7',
            field=models.TextField(default='desc_7'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_8',
            field=models.TextField(default='desc_8'),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_9',
            field=models.TextField(default='desc_9'),
        ),
    ]
