# Generated by Django 5.0.7 on 2024-08-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayurweb', '0003_remove_service_service_desc_service_desc_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='desc_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_10',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_11',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_12',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_13',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_14',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_15',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_16',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_4',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_5',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_6',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_7',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_8',
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc_9',
        ),
    ]
