# Generated by Django 5.0.7 on 2024-08-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayurweb', '0004_remove_service_desc_1_remove_service_desc_10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='military_trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='heading', max_length=500)),
                ('sub_heading', models.TextField(default='sub_heading')),
                ('desc', models.TextField(default='description')),
            ],
        ),
    ]
