# Generated by Django 5.0.7 on 2024-08-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayurweb', '0005_military_trans'),
    ]

    operations = [
        migrations.CreateModel(
            name='keynote_speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='heading', max_length=1000)),
                ('desc', models.TextField(default='description')),
            ],
        ),
    ]
