# Generated by Django 5.0.7 on 2024-08-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayurweb', '0006_keynote_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='motivate_speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='heading', max_length=500)),
                ('intro', models.TextField(default='intro')),
                ('why_choose', models.TextField(default='why choose me')),
                ('desc', models.TextField(default='description')),
            ],
        ),
    ]
