# Generated by Django 5.0.7 on 2024-08-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayurweb', '0007_motivate_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='Title of the Service', max_length=200)),
                ('icon_class', models.CharField(help_text='fa-solid fa-star', max_length=100)),
                ('desc', models.TextField(default='description')),
            ],
        ),
    ]
