# Generated by Django 5.0.7 on 2024-08-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayurweb', '0009_military_trans_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='military_trans',
            name='img',
            field=models.ImageField(default='image', upload_to=''),
        ),
    ]
