# Generated by Django 5.0.7 on 2024-09-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayurweb', '0014_gallery_seminar2_delete_gallery_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='https://emifreecar.com/images-new/offcer-coming-soon.jpg', upload_to='gallery/achievements')),
            ],
        ),
    ]
